# Generated by Django 3.0.8 on 2020-07-11 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Busqueda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busqueda', models.CharField(max_length=30)),
                ('precio_max', models.IntegerField(verbose_name='Precio máximo')),
                ('precio_min', models.IntegerField(verbose_name='Precio mínimo')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.CharField(max_length=30)),
                ('titulo', models.CharField(max_length=80)),
                ('precio', models.IntegerField()),
                ('link', models.URLField()),
                ('fecha', models.DateField()),
                ('busqueda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiforms.Busqueda')),
            ],
        ),
    ]
