# Generated by Django 3.0.7 on 2020-07-12 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiforms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultado',
            options={'ordering': ['fecha']},
        ),
    ]
