# Generated by Django 3.0.7 on 2020-07-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiforms', '0002_auto_20200712_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
